version: '3.3'
services:
  feishu-chatgpt:
    container_name: feishu-chatgpt
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000/tcp"
    # volumes:
    #   - ./code/config.yaml:/app/config.yaml:ro
    environment:
      APP_ID: "${APP_ID}"
      APP_SECRET: "${APP_SECRET}"
      APP_ENCRYPT_KEY: "${APP_ENCRYPT_KEY}"
      APP_VERIFICATION_TOKEN: "${APP_VERIFICATION_TOKEN}"
      # 请确保和飞书应用管理平台中的设置一致
      BOT_NAME: "${BOT_NAME}"
      # OpenAI API Key 支持负载均衡, 可以填写多个 Key 用逗号分隔
      OPENAI_KEY: "${OPENAI_KEY}"
      # 服务器配置
      HTTP_PORT: "${HTTP_PORT}"
      HTTPS_PORT: "${HTTPS_PORT}"
      USE_HTTPS: "${USE_HTTPS}"
      CERT_FILE: "${CERT_FILE}"
      KEY_FILE: "${KEY_FILE}"
      # OpenAI 地址, 一般不需要修改, 除非你有自己的反向代理
      API_URL: "${API_URL}"
      # 代理设置, 例如 - HTTP_PROXY=http://127.0.0.1:7890, 默认代表不使用代理
      HTTP_PROXY: "${HTTP_PROXY}"
